import { ArticleContent, NewsArticle, PodcastContent, VideoContent } from "@types";


const articleContent_0: ArticleContent = {
   author: "AJ HESS",
   pfp: "hess.jpg",
   date: "03/27/2023",
   image: "/news/article-000.jpg",
   imageCaption: "(Source images: Marvin Dott/Getty Images, Milad Fakurian/Unsplash)",
   paragraphs: [
    "Companies founded by women received less than 2% of venture capital funding in 2022—a decline from the year before. However, when women-led startups are funded, research has shown that they generate more in cumulative returns, compared to those led by men. A new VC fund aims to take this lesson to women's sports.",
    "On Monday, venture capitalists Kara Nortman and Jasmine Robinson announced the close of a $100 million fund, the Monarch Collective, with a mission to “accelerate equity in global sport.” Nortman is a former partner at the Los Angeles-based venture capital firm Upfront Ventures. Robinson was a partner at Causeway, a fund focused on sports, media, and entertainment.",
    "The Monarch Collective, founded in January, will focus on investing in women's teams and leagues, along with adjacent industries, such as media and gaming. The duo say they are initially considering investments in women's soccer teams in the U.S., and in women's teams and leagues in sports such as basketball, cycling, and rugby internationally.",
    "Last spring, Nortman cofounded Angel City FC, the Los Angeles-based National Women's Soccer League team—and the first majority female-owned professional sports franchise in the U.S. According to Nortman, professional women's sports—which are just starting to break through on television, with sponsors, and among fans—present an opportunity for large returns. Nortman calls it “an arbitrage on sexism.”",
    "“There's an opportunity to get in at what should be historically low valuations in teams and leagues, that are at the beginning of a media rights cycle—which is a very well understood revenue stream,” Nortman says. “So, if you're disciplined, if you have the right fund size, if you're showing up and actually doing work, you can get venture-like returns with very low risk.”",
    "Monarch Collective's advisors include sports industry leaders such as Paraag Marathe, president of 49ers Enterprises, the VC arm of the San Francisco 49ers; Becca Roux, executive director of the U.S. Women's National Team Players' Association, for soccer; and DeMaurice Fitzgerald Smith, executive director of the National Football League Players' Association. Several influential tech executives have also signed on as advisors including Lydia Jett, managing partner at SoftBank; Laela Sturdy, managing partner at CapitalG; and Ashley Still, senior vice president at Adobe. The fund's investors includes tennis star Billie Jean King and Sarah Harden, CEO of Hello Sunshine.",
    "Nortman, who rowed crew for four years at Princeton University, says she was inspired to start investing in women's sports as a result of her experience analyzing potential industries prime for growth. ",
    "“I went to the 2015 Women's World Cup finals in Vancouver with my girls and my husband. That's what activated me as a consumer and, ultimately, as a founder and now investor,” she says. “After the game, I literally couldn't find a jersey to buy, and I couldn't find content to watch.” She likens the experience to enjoying, and even paying for, a 90-minute Budweiser commercial, but not being able to buy any Budweiser afterward.",
    "“You have a billion people watching something,” says Nortman, referencing the more than 1.2 billion viewers who watched the most recent Women's World Cup tournament. “And they have nowhere to go. So, you really have no idea how big the market is, or could be.”",
    "LEVELING THE PLAYING FIELD",
    "The emergence of a fund like the Monarch Collective marks the next big step in the evolution of women's sports. The past century has been marked by moments of progress: the 1900 Olympic Games, which included women for the first time; the 1972 passage of Title IX, which required federally funded institutions to financially support women's and men's sports equally; and the 2019 Women's FIFA World Cup, which drew 1.2 billion viewers making it the most-watched women's sporting event of all time.",
    "When the U.S. Women's National Soccer Team won the 2019 World Cup, the stadium of 57,900 fans chanted for the players to receive the same pay as the men's team. The high-profile victory on the pitch launched a string of highly publicized legal proceedings, inspired support from lawmakers, and eventually led to the signing of equal pay agreements between the U.S. men's and women's teams last September. ",
    "Most recently, there has been an influx of investment in women's sports including from venture capital funds, video game companies, advertisers, governments, and celebrities. Many say that investing in women's sports can offer high returns, while advancing gender equity.",
    "Danette Leighton, CEO of the Women's Sports Foundation, a nonprofit dedicated to increasing girls' and women's involvement in sports, says her organization has noticed a “growing groundswell of investment” in women's sports that she hopes will “pave a path to progress for more sponsorship dollars, media coverage, and pay equity, for women both on and off the field of play—in the front office, the boardroom, and beyond.” Indeed, a 2018 study by Ernst & Young found that 94% of women who hold C-suite positions are former athletes.",
    "CONTENT AND SPONSORSHIPS",
    "For Robinson, who previously served as the manager of investments and business operations for the San Francisco 49ers, as well as a partner at Causeway, content and distribution are the keys to success for professional sports.",
    "Robinson's father played in the NFL, and she says she's long studied what made the NFL take off and grow in the way that it did. “To me, it was [because of] their content distribution dynamics, and TVs becoming really prevalent across American households, as well as how the NFL captured the cultural moment,” she says.",
    "Today, it's women's sports that are capturing the public conversation. “These cultural moments, combined with new media and content distribution opportunities,” she says, “create this unique moment where women's sports can scale and grow.”",
    "Sports content distribution powerhouses such as ESPN have seen a dramatic increase in investment in advertising during women's sports. In 2020, Ally Financial announced a five-year “50/50 Pledge,” vowing to reach parity across its paid media spending in men's and women's sports. Ally followed up this March by announcing a multimillion-dollar ad buy with Disney that requires 90% of its investment to be put to women's sports, through expanding game highlights, branded content, and features across ESPN.",
    "“For too long, women's sports programming has been treated as an afterthought in the media buying process,” says Andrea Brimmer, Ally's chief marketing and public relations officer. That doesn't just limit exposure for athletes; it also makes it harder for teams to land lucrative brand sponsors. Ally wants to change that dynamic: “Every dollar invested in women's sports helps our brand grow alongside it,” Brimmer says.",
    "Last year, Google announced a multi-year partnership with sports website The Athletic to double the amount of women's sports coverage. Overall, women's professional sports sponsorships grew 20% in 2022. ",
    "OpenSponsorship, a digital marketplace that connects brands with athletes—and whose investors include NBA team owners and Serena Williams—has facilitated more than 14,000 deals since launching in 2015 for brands such as Walmart, Footlocker, and Fanduel. Roughly 5,000 of these brand deals, worth a collective $6 million, have gone to women athletes. The platform currently has more than 16,000 athletes, including approximately 3,500 female athletes who play 125 sports across more than 65 countries.",
    "The growth in women's sports sponsorships comes from brands wanting to market to women and to align with the messaging of women's sports, says Ishveen Jolly, founder and CEO of OpenSponsorship. She adds that sponsorships with women athletes as individuals, as well as their teams, can be relatively affordable and be distributed to large audiences across social media. ",
    "“Back in the day, if you were sponsoring an athlete, you would have to do TV commercials and buy billboards and radio ads,” says Jolly, explaining that this led to brands primarily partnering with the most famous, often male, athletes. “Now brands have realized ‘Hey, if you're a female athlete with 100,000 followers, you have value. And we can just pay you directly and I don't need media buys and production, all of these extra costs.'”",
    "THE RETURN ON INVESTMENT",
    "Even if women's sports don't quite reach the size of men's in the near future, investors see a period of immense growth ahead, with broadcasters and brands embracing athletes and teams alike.",
    "This dynamic amounts to “the highest ROI opportunity in the sports ecosystem,” says Robinson. “You're buying into a market size that I would say is heavily depressed . . . [women's sport] make up less than a 10th of a percent of the size of the men's sports ecosystem, in terms of the revenue generated. So, even if you believe women's sports is going to become just 1% of the overall sports market, that's 10x market size growth.” ",
    "“There is tremendous value in women's leagues, teams, and athletes,that can positively impact the bottom line,” says Leighton of the Women's Sports Foundation. “It's high time for women's sports investments to shift from being a ‘trend' to being standard practice—that's just smart business, period.”",
  ],
   twitter: "https://twitter.com/AbigailJHess",
   linkedin: "https://www.linkedin.com/in/abigail-johnson-hess/",
}
const articleContent_1: ArticleContent = {
  author: "SHLOMO SPRUNG",
  pfp: "/images/news/Shlomo-1.jpg",
  date: "09/20/2023",
  image: "/news/article-001.jpg",
  imageCaption: "(Maja Hitij / FIFA via Getty Images)",
  paragraphs: [
    "A minority stake in the newly awarded NWSL expansion club in Boston is Monarch's first investment. Boardroom catches up with collective co-founder Kara Nortman.",
    "Kara Nortman co-founded the NWSL's Angel City soccer club in Los Angeles in 2020, quickly helping the team build to a $100 million valuation in a historically successful launch. Now, in 2023, it attempts to become the first-ever $1 billion women's sports team",
    "Earlier this year, Nortman spoke with Boardroom upon launching Monarch Collective alongside Jasmine Robinson, a $100 million investment fund solely focused on women's sports with backing from power players like Billie Jean King. Monarch's first investment is a minority stake in a new NWSL club in Boston announced Tuesday, set to launch in 2026 with only the second US professional stadium specifically constructed with women's soccer in mind.",
    "Boston Unity Soccer Partners consists of an all-female core ownership group led by Juno Equity Founder and Boston Celtics minority stakeholder Jennifer Epstein as controlling partner, with 95% of the invested capital from women and 40% from women of color. In July 2022, Nortman had a tech-related meeting with Flybridge Capital General Partner Anna Palmer, another member of the Boston core ownership group, but all Kara & Anna could talk about was soccer. That conversation led Palmer to form a group looking to bid on an NWSL expansion team, helping in the process before she even knew Monarch Collective would launch.",
    "“My upbringing on the investor side was through soccer, and it woke me up to what was possible in building Angel City. It started from a place of passion and purpose, and then it moved to the fastest growing revenue business I've ever seen, even including those in tech,” Nortman told Boardroom.",
    "“So it just felt natural that our first investment would end up in soccer.”",
    "Nortman said she worked collaboratively with the league on a policy to ensure there's no conflict of interest, as she now serves as a minority investor for two NWSL clubs, Angel City and the to-be-named Boston expansion project. Nortman is not the controlling owner of either team, nor will she be involved in their sporting decisions, she said. For the former Upfront Ventures managing partner, it's about bringing the right people and the right capital to the NWSL and women's sports, building a pipeline of talent through Monarch Collective to send to many teams to help leagues thrive.",
    "That mindset is part of what Kara Nortman called open source models for women's sports success. That means sharing best practices to get teams and leagues better media deals, grow attendance numbers, attract better ownership groups, and increase franchise valuations across the board.",
    "“At Angel City, anybody who wants to call me, I'll get on the phone and share high level numbers, our model, the kinds of key hires we made in the beginning,” Nortman said.",
    "Robinson spent more than three years as an investments and business operations manager with the San Francisco 49ers, helping the team move from the antiquated Candlestick Park to Levi's Stadium. She was in charge, Nortman said, of everything from the new stadium's wine program to negotiating an on-site merch contract with Fanatics and how much season ticket holders should pay for seats at a new stadium. These are types of elements that Monarch will bring to the Boston club as it looks to build a modernized new venue at George R. White Stadium in Franklin Park.",
    "Like Los Angeles, Boston is a historic sports town with so many entrenched champions with followings that span generations, making building a team from scratch a unique challenge. The biggest keys to building up an NWSL franchise, Nortman said, is building community, finding talent, and showing up with strength. It'll be vital to not only find the right people to grow the team but also build a stadium accessible to the demographics and populations that are lined up with the modern fan base. Nortman said she found the first two Angel City fans at an LAFC game, and it'll be up to women's soccer diehards like Palmer to attract fans and build up a diverse set of revenue streams.",
    "Showing up with strength means believing in the product you're selling, getting a fan base to buy in and help write the first chapter in the team's history together while taking best practices from teams like the Celtics and Red Sox who have executives in the new ownership group. It's about bringing in the right heads of revenue, heads of community, and executing on everything from best ticketing practices, building a supporters group, finding the right margin structures and sponsorship deals. Nortman believes women's teams actually have an advantage in sponsorships, with new brands in beauty, supplements, and alcohol focused on women's consumption gravitating toward them in addition to the influx of traditional sponsors.",
    "Of course, this Boston club is just the first of what promises to be many Monarch Collective investments in women's sports, with the fund closed and the group's first hires coming soon. Nortman said Monarch is looking at global soccer, women's basketball, golf, tennis, and media rights, striking a balance between being disciplined, thoughtful, collaborative, intentional, and bullish.",
    "“The dollars are so big and people are having to make such big moves on the men's side that there should be more room to just innovate on the women's side,” she said. “But it takes focus and purpose to do it.”",
    "With this investment in the NWSL's 15th and newest club, Kara Nortman is hopeful that this is only the beginning of Monarch's reign.",
  ],
  twitter: "https://twitter.com",
  linkedin: "https://boardroom.tv/author/shlomo-sprung/",
  instagram: "https://instagram.com",  
  email: "example@email.com",  
}
const articleContent_2: ArticleContent = {
  author: "KARA NORTMAN",
  pfp: "pfp.png",
  date: "03/27/2023",
  image: "/news/monarch.jpg",
  imageCaption: "",
  paragraphs: [
    "Today we announce Monarch Collective, an investment fund exclusively focused on investing in women's sports.", 
    "Monarch Collective was founded by Jasmine Robinson and myself through a shared conviction that sports can change hearts, minds and culture. In order to do it, we believe that equity in investment and representation is critical for success.",
    "I launched Angel City Football Club with my co-founders in 2019 after years of dreaming about a big, splashy women's soccer team rooted in my hometown. I could say I never imagined that after just one season, we'd generate tens of millions of dollars in revenue and sign teen phenom Alyssa Thompson, one of the best players in the world. But that would be a lie.",
    "I knew it was possible. And that's because I have never seen a greater opportunity than the one I have experienced in women's sports.", 
    "I grew up in Los Angeles and can still remember the cracked soccer pitch at Balboa Park in the San Fernando Valley. This pitch was the first place I learned how to lose; it was the first place that taught me I didn't need to be perfect. It's where I first started to feel I belonged and a community sprouted up around me. I felt joyful.",
    "I was a child then. And it took over 30 years for me to realize that this same feeling could be replicated in business.",
    "After attending Princeton University and Stanford Business School, I spent the last 25 years as an investor and operator in both early stage and established large companies at a moment in time when women's sports has characteristics that will benefit from a diverse set of skills.    ", 
    "In Hollywood screenplays, they say there's always an inciting incident. The 2015 Women's World Cup Finals was mine. I watched in person as the US scored five electric goals, breaking the record for most goals in a final. The win made the US the only country to bring home three Women's World Cups. Nearly 27 million people watched the game on T.V. in the U.S alone, making it the most-watched soccer game in history at the time — for men or women.    ",
    "But as I left the Vancouver stadium, practically levitating with energy, I couldn't find jerseys to buy for my daughters. And when I returned home to L.A., I couldn't find the powerhouse players I had just lost my voice screaming for anywhere on TV.    ",
    "The investor in me thought: I'm a fan and am looking to deepen my experience after just watching the most exhilarating game in recent history. Why won't anyone take my money?", 
    "It wasn't hard to find the data once I went looking for it. Every year, billions of dollars are being invested in the global sports ecosystem, but less than 1% is allocated to women's sports.",
    "And yet: women's sports has a large, young, and engaged fan base and its revenue is growing faster than other major sports leagues.    ",
    "The timing also felt right: it's a dynamic ecosystem where teams are being added as we speak, and new communities of fans are emerging to better represent their communities. While these ideas brewed in the back of my mind, I was excited to talk to friends I respected in the sports world, thinking maybe going all-in on a women's team was a decent idea.    ", 
    "But the overwhelming consensus was that people only wanted to watch women play soccer once every four years. That I was, in fact, one of the only people who wanted a more frequent experience. I called BS.    ",
    "Then TIME'S UP happened.",
    "So many people showed up and did a lot of work catalyzed by an issue that felt irrefutably wrong. They became my people. Most of us got to where we were in our careers because we did not like to fail. We earned our degrees, did all the “right” things, and worked hard to fit in… so that perhaps some day we could stand out.", 
    "But I felt something different with this group. We were focused on building a strong female community and it was the first time I felt bound by a common purpose. I realized that you can make a lot of money fitting in, but it's pretty hard to change systems that way. And we wanted to see things change.    ",
    "Here's how it worked for me in the years leading up to Angel City: I did my full-time job at Upfront Ventures all week and then worked my second, unpaid job until 2 AM on weekends. I planned my vacations around US Women's National Team friendlies and important matches in other countries. I showed up to meet players and union leaders. I asked a lot of questions and I was eager to learn.    ",
    "In hindsight, I'll admit that you don't just wake up one day at 44-years-old realizing you want to start a professional sports team. It's probably always been there.    ", 
    "After years of grinding to build the team and the business from the ground up with people like Natalie Portman, Eva Longoria, and Abby Wambach, Angel City played its debut match at BMO Stadium in March 2022 to a sold out crowd. This month, we kicked off our second season to another sold out crowd and a 95% season ticket renewal rate.    ",
    "There would be no Monarch Collective to announce today without the success of Angel City.",
    "One of our dreams for Monarch is to show the world that fans will pay as much to watch women as they will men. While both men and women watch sports in nearly equal numbers, women control more discretionary spend than people realize, making them a highly coveted demographic for brands and media companies.    ",
    "Angel City is just one team, in one city, playing one sport. What we saw with our L.A. team is now happening in the US and all over the world. People are packing women's soccer stadiums not only in Kansas and North Carolina, but in Newcastle, England and Barcelona, Spain.    ", 
    "And it's not just soccer. Similar fervor is spreading out like an inkblot — as women's sports engagement is up all over the world. Rugby in New Zealand, cricket in India, cycling in France, and NCAA basketball and volleyball in the US.    ",
    "The growing numbers show women's sports fans want to be part of something new. They have been underserved and, at times, even ignored by too many hundred-year-old sports communities.    ",
    "We hope Monarch can be part of writing a new story. ",
    "As an athlete and VC investor, I am hardwired for teamwork. I knew from the start that if I wanted to build something meaningful, I needed to find a true co-founder and partner. That's where Jasmine Robinson, Monarch's co-founder, enters the story.", 
    "Jasmine grew up the daughter of an NFL player at a time when salaries were low and media revenue was nascent. She's had a unique backstage pass to the player's side of the business during the incredible growth of the NFL. It's a point of view most people in our industry will never experience.    ",
    "Her lifelong passion for sports led her to the San Francisco 49ers but it was her love of taking on hard, meaningful challenges and her unparalleled intellectual curiosity (she studied linguistics, neurobiology, and computer science at Harvard) that stopped me in my tracks.    ",
    "Jasmine joined the 49ers from Bain at an important moment in time. They were in the process of building the largest privately financed stadium and had an opportunity to change the revenue profile of the team — which they did — moving from the bottom of the league to the top.    ",
    "Jasmine worked on nearly every aspect of the 49ers' business and learned from some of the best in the business — she was involved in negotiating key licensing deals, optimizing the margin profile of core revenue streams, and designing elements of the fan experience. She then joined Causeway where she invested in everything from emerging sports leagues to innovative sports media companies.    ",
    "Building Monarch with Jasmine felt like a no-brainer. She is equal parts brilliant and practical; she knows when to take risks and when to stay the course.", 
    "Together, Jasmine and I are dedicated to meeting each opportunity with “what's best for this situation” and not “what is our fund's strategy.”    ",
    "Both how and who will be investing in women's sports is important. Women's sports syndicates should represent their community and be built with an eye toward what each investor brings to the table.    ",
    "Monarch aspires to be an influential, “change agent” type of equity product for teams and leagues at critical moments in their evolution. We hope to come with a collaborative mindset that welcomes other co-investors and a commitment to providing hands-on support to scale the businesses we partner with.    ",
    "At a time of cultural division and decaying trust in institutions, sports is the universal language that unites us. It's where fashion, art, music and politics all collide in a version of socially acceptable tribalism. It's a universal language that gets everyone's attention.    ",
    "On game day, these stadiums become our houses of prayer — the place where people have come together for generations to share the most primal feelings of despair and joy (depending on the scoreboard).    ",
    "It's this concept of joy that's kept us buzzing at night as we built Monarch. That same feeling of joy I felt exiting the World Cup stadium eight years ago. Investing models driven by joy can generate change more powerfully than investing models driven by greed.    ",
    "At Monarch, we plan to show up with capital, a collaborative mindset, and joy to be a part of growing our women's sports community.    ",
  ],
  twitter: "https://twitter.com/karanortman",
  linkedin: "https://www.linkedin.com/in/karanortman/",
}
const articleContent_3: ArticleContent = {
  author: "STEPH YANG",
  pfp: "pfp.png",
  date: "09/20/2023",
  image: "/news/ballon.jpg",
  imageCaption: "",
  paragraphs: [
    "On a bright, blustery day in front of Boston City Hall, the primary ownership group of the newest NWSL expansion team gathered alongside Mayor Michelle Wu to announce its intentions to operate a professional women’s soccer team in the city. Joining the group for the event was Monarch Collective managing partner Jasmine Robinson, a former San Francisco 49ers investment and business operations manager and someone with experience in venture capital funding in sports and media. Monarch Collective, an investment fund that includes Angel City co-founder Kara Nortman among its members, counts this Boston expansion team as its first investment.",
    "Robinson spoke to The Athletic before the announcement to discuss why she and Monarch decided to come on board as investors, her view of the evolving women’s soccer landscape and Boston’s next moves as it prepares for its 2026 debut.",
    "This interview has been lightly edited for length and clarity.",
    "How did you get involved with Monarch and then with Boston? ",
    "...",
  ],
  twitter: "https://twitter.com/thrace",
  linkedin: "https://www.linkedin.com/in/stephanieyangjd/",
}
const videoContent: VideoContent = {
  author: "Samantha Musanga",
  date: "03/27/2023",
  url: "https://www.youtube.com/embed/KnumAWWWgUE?si=Sf5Y9SltT-HCZfDz"
}

const podcastContent_1: PodcastContent = {
  author: "FEG Insight Bridge",
  date: "10/10/2023",
  image: "/news/soccer-mom.jpg",
  subTitle:"Full Time with Meg Linehan: A Show about women's soccer",
  paragraphs: [
   "Immerse yourself in the world of investing in sports as Greg Dowling sits down with prominent American venture capitalist, Kara Nortman.",
   "Kara, shares her journey in becoming a co-founder of Angels City FC, as well as her role at  Monarch Collective, a venture capital firm investing in women's sports, teams, leagues, and adjacent revenue streams. Discover investment strategies, challenges, and triumphs that shaped these groundbreaking women-led sports ventures. Kara breaks down underwriting, expanding media rights, commercialization, and maximizing returns, providing insight for investors. Kara provides raw and unfiltered insights into the dynamic world of sports investing. Join us, we hope you get a kick out of it.   ",
   "You can find every episode of FEG Insight Bridge podcasts in one place and sign up to receive our other publications here.   ",
 ],
  url: "https://podcasts.apple.com/us/podcast/soccer-mom-to-sports-magnate/id1572017407?i=1000630808166",
  url2: "https://podcasts.apple.com/us/podcast/feg-insight-bridge/id1572017407",
}
export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 0,
    title: "Introducing Monarch Collective: Going All-In on Women's Sports",
    content: articleContent_2,
    type: "article",
    readTime: 7,
    image: "monarch.jpg",
    externalUrl: "https://ventureinside.com/introducing-monarch-collective-going-all-in-on-womens-sports-c009cc393448"
  },
  {
    id: 1,
    title:
      "Kara Nortman & Monarch Begin Reign with NWSL Boston Investment",
    content: articleContent_1,
    type: "article",
    readTime: 5,
    image: "article-001.jpg",
    externalUrl: "https://boardroom.tv/kara-nortman-monarch-nwsl-boston-expansion/"
  },
  {
    id: 2,
    title: "Soccer Mom to Sports Magnate",
    content: podcastContent_1,
    type: "podcast",
    readTime: 45,
    image: "soccer-mom.jpg",
    externalUrl: "https://podcasts.apple.com/us/podcast/feg-insight-bridge/id1572017407"
  },
  {
    id: 3,
    title: "Boston's NWSL ownership made 'full sprint' for its bid: An investor explains how it came together",
    content: articleContent_3,
    type: "article",
    readTime: 7,
    image: "ballon.jpg",
    externalUrl: "https://theathletic.com/4882270/2023/09/20/boston-nwsl-2026/"
  },
  {
    id: 4,
    title: "The Monarch Collective unveils $100 million fund to bring equity to women's sports",
    content: articleContent_0,
    type: "article",
    readTime: 7,
    image: "article-000.jpg",
    externalUrl: "https://www.fastcompany.com/90871005/monarch-collective-100-million-fund-equity-womens-sports"
  },
];